repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier
        entry: npx prettier --write
        language: node
        types: [file]
        files: \.(ts|tsx|js|jsx|json|css|md)$

      - id: eslint
        name: eslint
        entry: npx eslint --max-warnings 0
        language: node
        types: [file]
        files: \.(ts|tsx|js|jsx)$
        pass_filenames: false
